myapp/urls.py
from django.urls import path
from myapp.views import *

app_name = "myapp"

urlpatterns = [
    path('', dashboard, name="dashboard"),
    path('filter-by-month/', filterbymonth, name="filterbymonth"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, documenet_root=settings.STATICFILES_DIRS)

myapp/models.py
from django.db import models

# Create your models here.
class PurchaseModel(models.Model):

    purchaser_name = models.CharField(max_length=120)
    quantity = models.IntegerField(default=0)


class PurchaseStatusModel(models.Model):
    status_choices = (
        ("open", "Open"),
        ("verified", "Verified"),
        ("dispatched", "Dispatched"),
        ("delivered", "Delivered"),
    )

    purchase = models.ForeignKey(PurchaseModel, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=status_choices)
    created_at = models.DateTimeField(auto_now_add=True, editable=True)

myapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse

# import models
from myapp.models import *

# third party library
import random

# Create your views here.
def dashboard(request):
    template_name = 'myapp/index.html'
    purchase_status_model_obj = PurchaseStatusModel.objects.all()
    
    x_axis_data = ''
    y_axis_data = ''
    random_objs = random.sample(list(purchase_status_model_obj), 10)

    total = 0
    for ran_data in random_objs:
        x_axis_data += str(ran_data.purchase.purchaser_name) + ','
        y_axis_data += str(ran_data.purchase.quantity) + ','
        total += ran_data.purchase.quantity

    print("Average--",total/10)
    status_list = dict(PurchaseStatusModel._meta.get_field('status').choices)
    return render(request, template_name, {'x_axis_data':x_axis_data, 'y_axis_data':y_axis_data, 'status_list':status_list})

def filterbymonth(request):
    if request.method == "POST":
        try:
            datefilter = request.POST['datefilter']
            selected_status = request.POST["selected_status"]
            
            if len(datefilter) > 0 and len(selected_status) > 0:
                splited_date = datefilter.split('-')
                purchase_status_model_obj = PurchaseStatusModel.objects.filter(status=selected_status, created_at__year=splited_date[1], created_at__month=splited_date[0])
            else:
                if len(datefilter) > 0:
                    splited_date = datefilter.split('-')
                    purchase_status_model_obj = PurchaseStatusModel.objects.filter(created_at__year=splited_date[1], created_at__month=splited_date[0])
                else:
                    purchase_status_model_obj = PurchaseStatusModel.objects.filter(status=selected_status)

            x_axis_data = ''
            y_axis_data = ''
            random_objs = random.sample(list(purchase_status_model_obj), 10)

            total = 0
            for ran_data in random_objs:
                x_axis_data += str(ran_data.purchase.purchaser_name) + ','
                y_axis_data += str(ran_data.purchase.quantity) + ','
                total += ran_data.purchase.quantity
            print("Average--",total/10)
            return JsonResponse({'x_axis_data':x_axis_data, 'y_axis_data':y_axis_data})
        except:
            return redirect('/')

templates/myapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/style.css'%} ">

        <!-- Date Picker -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
        <!-- including ECharts file -->
        <script src="{% static 'js/echarts.min.js' %}"></script>
        <!-- Ajax -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- jQury -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <!-- Date Picker -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
        
    </head>
    <body>
        <div class="container">
            <br>
            {% block content %} {% endblock %}
            <br>
        </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
    </body>
</html>

templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
    <!-- prepare a DOM container with width and height -->
    <div id="main" style="width: auto;height:500px;"></div>
    <hr>
    <div class="row">
        <div class="col-4">
            <input type="text" class="form-control" name="datepicker" id="datepicker" placeholder="Choose a date"/>
        </div>
        <div class="col-4">
            <select class="form-control" name="status" id="status">
                <option value="">---------- Select Status ----------</option>
                {% for key,value in status_list.items %}
                <option value="{{key}}">{{value}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    
    <script type="text/javascript">
        // Date Picker
        $("#datepicker").datepicker( {
            
            format: "mm-yyyy",
            startView: "months", 
            minViewMode: "months",
            todayHighlight: 1,
            
        });
        
        // echarts
        // based on prepared DOM, initialize echarts instance
        var myChart = echarts.init(document.getElementById('main'));
        
        x_axis = "{{x_axis_data}}";
        y_axis = "{{y_axis_data}}";
        
        x_axis_data = x_axis.split(',');
        y_axis_data = y_axis.split(',');
        x_axis_data.pop()
        y_axis_data.pop();
        
        
        // specify chart configuration item and data
        var option = {
            title: {
                text: 'Purchaser Model'
            },
            legend: {
                data:['Purchaser']
            },
            xAxis: {
                data: x_axis_data,
            },
            yAxis: {},
            series: [{
                name: 'Purchaser',
                type: 'bar',
                data: y_axis_data,
                
            }]
        };
        // use configuration item and data specified to show chart
        myChart.setOption(option);

        // Ajax for Date Picker
        $('#datepicker').on('change', function(event){
            event.preventDefault();
            var datefilter = $('#datepicker')[0].value;
            var selected_status = $('#status')[0].value;
            var token = '{{csrf_token}}';
            $.ajax({
                url: "{% url 'myapp:filterbymonth' %}",
                headers: { "X-CSRFToken": token },
                method: "POST",
                data:{
                    'datefilter': datefilter,
                    'selected_status': selected_status,
                },
                success: function(msg){
                    console.log("success--");
                    x_axis = msg.x_axis_data;
                    y_axis = msg.y_axis_data;
                    try{
                        x_axis_data = x_axis.split(',');
                        y_axis_data = y_axis.split(',');
                        x_axis_data.pop()
                        y_axis_data.pop();
                    }
                    catch{
                        x_axis_data = [];
                        y_axis_data = [];
                    }

                    // specify chart configuration item and data
                    var option = {
                        title: {
                            text: 'Purchaser Model'
                        },
                        legend: {
                            data:['Purchaser']
                        },
                        xAxis: {
                            data: x_axis_data,
                        },
                        yAxis: {},
                        series: [{
                            name: 'Purchaser',
                            type: 'bar',
                            data: y_axis_data,
                            
                        }]
                    };
                    // use configuration item and data specified to show chart
                    myChart.setOption(option);
                }
            });
        });

        // Ajax for Status
        $('#status').on('change', function(event){
            event.preventDefault();
            var datefilter = $('#datepicker')[0].value;
            var selected_status = $('#status')[0].value;
            var token = '{{csrf_token}}';
            $.ajax({
                url: "{% url 'myapp:filterbymonth' %}",
                headers: { "X-CSRFToken": token },
                method: "POST",
                data:{
                    'datefilter': datefilter,
                    'selected_status': selected_status,
                },
                success: function(msg){
                    console.log("success--");
                    x_axis = msg.x_axis_data;
                    y_axis = msg.y_axis_data;
                    try{
                        x_axis_data = x_axis.split(',');
                        y_axis_data = y_axis.split(',');
                        x_axis_data.pop()
                        y_axis_data.pop();
                    }
                    catch{
                        x_axis_data = [];
                        y_axis_data = [];
                    }

                    // specify chart configuration item and data
                    var option = {
                        title: {
                            text: 'Purchaser Model'
                        },
                        legend: {
                            data:['Purchaser']
                        },
                        xAxis: {
                            data: x_axis_data,
                        },
                        yAxis: {},
                        series: [{
                            name: 'Purchaser',
                            type: 'bar',
                            data: y_axis_data,
                            
                        }]
                    };
                    // use configuration item and data specified to show chart
                    myChart.setOption(option);
                }
            });
        });

    </script>
{% endblock %}